export default [
  {
    mentorId: "52101007",
    name: "Huỳnh Quốc Trường",
    nickname: "Kunzz",
    desc: "Tên: Huỳnh Quốc Trường Ngành học : Mạng máy tính và truyền thông dữ liệu Các công nghệ đang dùng: đang tìm hiểu cơ bản về reactjs Có thể hỗ trợ: phương pháp lập trình, lí thuyết cơ bản về ngôn ngữ C Định hướng tương lai: lập trình wed và ứng dụng Sở thích: học ra học chơi ra chơi",
    avt: "https://www.treasury.gov.ph/wp-content/uploads/2022/01/male-placeholder-image.jpeg",
    full: true,
  },
  {
    mentorId: "519K0013",
    name: "Nguyễn Đình Minh Khôi",
    nickname: "Khôi Chúa Hề 🤡",
    desc: "Chuyên về front end và một ít giải thuật mô hình, hướng nội nhưng social hơi kinh, đẹp trai và việc học phải gọi là đỉnh, cái gì cũng biết mỗi tội không biết cách biến em làm của riêng mình 🤡.",
    avt: "https://www.treasury.gov.ph/wp-content/uploads/2022/01/male-placeholder-image.jpeg",
    full: true,
  },
  {
    mentorId: "519K0014",
    name: "Nguyễn Đình Minh Khôi",
    nickname: "Khôi Chúa Hề 🤡",
    desc: "Chuyên về front end và một ít giải thuật mô hình, hướng nội nhưng social hơi kinh, đẹp trai và việc học phải gọi là đỉnh, cái gì cũng biết mỗi tội không biết cách biến em làm của riêng mình 🤡.",
    avt: "https://www.treasury.gov.ph/wp-content/uploads/2022/01/male-placeholder-image.jpeg",
    full: true,
  },
  {
    mentorId: "519K0015",
    name: "Nguyễn Đình Minh Khôi",
    nickname: "Khôi Chúa Hề 🤡",
    desc: "Chuyên về front end và một ít giải thuật mô hình, hướng nội nhưng social hơi kinh, đẹp trai và việc học phải gọi là đỉnh, cái gì cũng biết mỗi tội không biết cách biến em làm của riêng mình 🤡.",
    avt: "https://www.treasury.gov.ph/wp-content/uploads/2022/01/male-placeholder-image.jpeg",
    full: false,
  },
  {
    mentorId: "519K0016",
    name: "Nguyễn Đình Minh Khôi",
    nickname: "Khôi Chúa Hề 🤡",
    desc: "Chuyên về front end và một ít giải thuật mô hình, hướng nội nhưng social hơi kinh, đẹp trai và việc học phải gọi là đỉnh, cái gì cũng biết mỗi tội không biết cách biến em làm của riêng mình 🤡.",
    avt: "https://www.treasury.gov.ph/wp-content/uploads/2022/01/male-placeholder-image.jpeg",
    full: false,
  },
  {
    mentorId: "519K0017",
    name: "Nguyễn Đình Minh Khôi",
    nickname: "Khôi Chúa Hề 🤡",
    desc: "Chuyên về front end và một ít giải thuật mô hình, hướng nội nhưng social hơi kinh, đẹp trai và việc học phải gọi là đỉnh, cái gì cũng biết mỗi tội không biết cách biến em làm của riêng mình 🤡.",
    avt: "https://www.treasury.gov.ph/wp-content/uploads/2022/01/male-placeholder-image.jpeg",
    full: false,
  },
  {
    mentorId: "519K0018",
    name: "Nguyễn Đình Minh Khôi",
    nickname: "Khôi Chúa Hề 🤡",
    desc: "Chuyên về front end và một ít giải thuật mô hình, hướng nội nhưng social hơi kinh, đẹp trai và việc học phải gọi là đỉnh, cái gì cũng biết mỗi tội không biết cách biến em làm của riêng mình 🤡.",
    avt: "https://play-lh.googleusercontent.com/TcHgSH30vCBCtQfyFLWvvPJdpOAJrSp1OtqopwMue3yRiXa7wT5Fs8gUbA3oJylGW991",
    full: true,
  },
  {
    mentorId: "519K0019",
    name: "Nguyễn Đình Minh Khôi",
    nickname: "Khôi Chúa Hề 🤡",
    desc: "Chuyên về front end và một ít giải thuật mô hình, hướng nội nhưng social hơi kinh, đẹp trai và việc học phải gọi là đỉnh, cái gì cũng biết mỗi tội không biết cách biến em làm của riêng mình 🤡.",
    avt: "https://www.treasury.gov.ph/wp-content/uploads/2022/01/male-placeholder-image.jpeg",
    full: true,
  },
];
